Script test V5

diff --git a/.github/workflows/build_and_release.yml b/.github/workflows/build_and_release.yml
--- a/.github/workflows/build_and_release.yml
+++ b/.github/workflows/build_and_release.yml
@@ -74,14 +74,14 @@ jobs:
       # Step 5: Verify Output Files
       - name: Verify Output Files
         run: |
-          [ -f "color_palette_creator.app" ] || (echo "macOS build failed, file missing." && exit 1)
+          [ -f "color_palette_creator.bin" ] || (echo "macOS build failed, file missing." && exit 1)
 
       # Step 6: Upload Artifacts
       - name: Upload Artifacts
         uses: actions/upload-artifact@v3
         with:
           name: macos-build
-          path: color_palette_creator.app
+          path: color_palette_creator.bin
 
   build-windows:
     runs-on: windows-latest
@@ -116,12 +116,15 @@ jobs:
           Expand-Archive -Path upx.zip -DestinationPath upx
 
           # Move UPX executable to main `upx` folder for easier access
-          Move-Item -Path .\upx\*\upx.exe -Destination .\upx.exe
+          # Move-Item -Path .\upx\*\upx.exe -Destination .\upx.exe
+          # Add UPX to PATH
+          $env:Path += ";$(Resolve-Path .\upx\*)"
+
 
       # Step 5: Build executable with Nuitka
       - name: Build executable with Nuitka
         run: |
-          nuitka --onefile --standalone --upx-binary=upx.exe --windows-console-mode=disable --enable-plugin=upx --assume-yes-for-downloads --windows-icon-from-ico=assets/appl.ico --enable-plugin=tk-inter --enable-plugin=no-qt src/color_palette_creator.py
+          nuitka --onefile --standalone --windows-console-mode=disable --enable-plugin=upx --assume-yes-for-downloads --windows-icon-from-ico=assets/appl.ico --enable-plugin=tk-inter --enable-plugin=no-qt src/color_palette_creator.py
 
       # Step 6: Verify Output Files
       - name: Verify Output Files
