Script test V4

diff --git a/.github/workflows/build_and_release.yml b/.github/workflows/build_and_release.yml
--- a/.github/workflows/build_and_release.yml
+++ b/.github/workflows/build_and_release.yml
@@ -7,13 +7,8 @@ on:
   workflow_dispatch:
 
 jobs:
-  build:
-    strategy:
-      fail-fast: false
-      matrix:
-        os: [macos-latest, ubuntu-latest, windows-latest]
-        
-    runs-on: ${{ matrix.os }}
+  build-linux:
+    runs-on: ubuntu-latest
 
     steps:
       # Step 1: Checkout repository
@@ -32,11 +27,85 @@ jobs:
           python -m pip install --upgrade pip
           pip install -r requirements.txt
           pip install nuitka
-        shell: bash
 
-      # Step 4: Download and Install Latest UPX (Windows Only)
-      - name: Download and Install UPX (Windows Only)
-        if: runner.os == 'Windows'
+      # Step 4: Build executable with Nuitka
+      - name: Build executable with Nuitka
+        run: |
+          nuitka --onefile --standalone --windows-console-mode=disable --assume-yes-for-downloads --enable-plugin=tk-inter --enable-plugin=no-qt src/color_palette_creator.py
+
+      # Step 5: Verify Output Files
+      - name: Verify Output Files
+        run: |
+          [ -f "color_palette_creator.bin" ] || (echo "Linux build failed, file missing." && exit 1)
+
+      # Step 6: Upload Artifacts
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: linux-build
+          path: color_palette_creator.bin
+
+  build-macos:
+    runs-on: macos-latest
+
+    steps:
+      # Step 1: Checkout repository
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      # Step 2: Set up Python
+      - name: Set up Python 3.11
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.11
+
+      # Step 3: Install dependencies
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+          pip install nuitka
+
+      # Step 4: Build executable with Nuitka
+      - name: Build executable with Nuitka
+        run: |
+          nuitka --onefile --standalone --windows-console-mode=disable --assume-yes-for-downloads --macos-app-icon=assets/appl.icns --enable-plugin=tk-inter --enable-plugin=no-qt src/color_palette_creator.py
+
+      # Step 5: Verify Output Files
+      - name: Verify Output Files
+        run: |
+          [ -f "color_palette_creator.app" ] || (echo "macOS build failed, file missing." && exit 1)
+
+      # Step 6: Upload Artifacts
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: macos-build
+          path: color_palette_creator.app
+
+  build-windows:
+    runs-on: windows-latest
+
+    steps:
+      # Step 1: Checkout repository
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      # Step 2: Set up Python
+      - name: Set up Python 3.11
+        uses: actions/setup-python@v4
+        with:
+          python-version: 3.11
+
+      # Step 3: Install dependencies
+      - name: Install dependencies
+        run: |
+          python -m pip install --upgrade pip
+          pip install -r requirements.txt
+          pip install nuitka
+
+      # Step 4: Download and Install Latest UPX
+      - name: Download and Install UPX
         run: |
           # Fetch the latest release URL of UPX from GitHub API
           $latestRelease = Invoke-RestMethod -Uri "https://api.github.com/repos/upx/upx/releases/latest"
@@ -48,36 +117,52 @@ jobs:
 
           # Move UPX executable to main `upx` folder for easier access
           Move-Item -Path .\upx\*\upx.exe -Destination .\upx.exe
-        shell: pwsh
 
       # Step 5: Build executable with Nuitka
       - name: Build executable with Nuitka
         run: |
-          if [ "$RUNNER_OS" == "Linux" ] || [ "$RUNNER_OS" == "macOS" ]; then
-            nuitka --onefile --standalone --macos-app-icon=assets/appl.icns --enable-plugin=tk-inter --enable-plugin=no-qt src/color_palette_creator.py
-          elif [ "$RUNNER_OS" == "Windows" ]; then
-            nuitka --onefile --standalone --macos-app-icon=assets/appl.icns --upx-binary=upx.exe  --windows-console-mode=disable --enable-plugin=upx --assume-yes-for-downloads --windows-icon-from-ico=assets/appl.ico --enable-plugin=tk-inter --enable-plugin=no-qt src/color_palette_creator.py
-          fi
-        shell: bash
+          nuitka --onefile --standalone --upx-binary=upx.exe --windows-console-mode=disable --enable-plugin=upx --assume-yes-for-downloads --windows-icon-from-ico=assets/appl.ico --enable-plugin=tk-inter --enable-plugin=no-qt src/color_palette_creator.py
 
       # Step 6: Verify Output Files
       - name: Verify Output Files
         run: |
-          FILES_MISSING=0
-          if [ "$RUNNER_OS" == "Linux" ] || [ "$RUNNER_OS" == "macOS" ]; then
-            [ -f "color_palette_creator.bin" ] || FILES_MISSING=1
-          elif [ "$RUNNER_OS" == "Windows" ]; then
-            [ -f "color_palette_creator.exe" ] || FILES_MISSING=1
-          fi
-          if [ "$FILES_MISSING" -eq 1 ]; then
-            echo "One or more output files are missing. Skipping release."
+          if (!(Test-Path -Path "color_palette_creator.exe")) {
+            Write-Error "Windows build failed, file missing."
             exit 1
-          fi
-        shell: bash
+          }
 
-      # Step 7: Create GitHub Release (if files are present)
+      # Step 7: Upload Artifacts
+      - name: Upload Artifacts
+        uses: actions/upload-artifact@v3
+        with:
+          name: windows-build
+          path: color_palette_creator.exe
+
+  release:
+    needs: [build-linux, build-macos, build-windows]
+    runs-on: ubuntu-latest
+
+    steps:
+      # Step 1: Checkout repository
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      # Step 2: Download Artifacts
+      - name: Download Artifacts
+        uses: actions/download-artifact@v3
+        with:
+          name: linux-build
+      - name: Download Artifacts
+        uses: actions/download-artifact@v3
+        with:
+          name: macos-build
+      - name: Download Artifacts
+        uses: actions/download-artifact@v3
+        with:
+          name: windows-build
+
+      # Step 3: Create GitHub Release
       - name: Create GitHub Release
-        if: success()  # Only run if the previous steps were successful
         uses: softprops/action-gh-release@v1
         with:
           files: |
